env: stg

routes:
  dev:
    board: http://localhost:8080
    school: http://localhost:8080
    search: http://192.168.0.17:8080
  stg:
    board: board:8080
    school: school:8080
    search: search:8080
