routes:
  dev:
    board: http://localhost:8080
    school: http://localhost:8080
    search: http://localhost:8080
    user: http://localhost:8080
  stg:
    board: http://board:8080
    school: http://school:8080
    search: http://search:8080
    user: http://user:8080
