routes:
  dev:
    user: http://localhost:8080
    school: http://localhost:8081
    board: http://localhost:8082
    search: http://localhost:8083
  stg:
    user: http://user:8080
    school: http://school:8080
    board: http://board:8080
    search: http://search:8080
    
